<!DOCTYPE html>
<html>
<head>
    <title>Student Report</title>

    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            font-size: 22px;
        }

        .header p {
            margin: 5px 0;
            font-size: 12px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
        }

        th {
            background-color: #2c3e50;
            color: #fff;
            padding: 8px;
        }

        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: center;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        .footer {
            margin-top: 15px;
            text-align: right;
            font-size: 10px;
            color: #777;
        }

        .badge {
            padding: 3px 6px;
            border-radius: 4px;
            color: #fff;
            font-size: 10px;
        }

        .active {
            background: #27ae60;
        }

        .inactive {
            background: #e74c3c;
        }
    </style>

</head>
<body>

<div class="header">
    <h1>Student Management System</h1>
    <p>Student Report Document</p>
    <p>Date: {{ date('Y-m-d') }}</p>
</div>

<table>
    <tr>
        <th>Reg No</th>
        <th>Name</th>
        <th>Email</th>
        <th>Address</th>
        <th>DOB</th>
        <th>Age</th>
        <th>Status</th>
        <th>Phone</th>
        <th>NIC</th>
    </tr>

    @foreach($students as $student)
        <tr>
            <td>{{ $student->reg_no }}</td>
            <td>{{ $student->name }}</td>
            <td>{{ $student->email }}</td>
            <td>{{ $student->address }}</td>
            <td>{{ $student->dob }}</td>
            <td>{{ $student->age }}</td>

            <td>
                @if($student->status == 'Active')
                    <span class="badge active">Active</span>
                @else
                    <span class="badge inactive">Inactive</span>
                @endif
            </td>

            <td>{{ $student->phone }}</td>
            <td>{{ $student->nic }}</td>
        </tr>
    @endforeach

</table>

<div class="footer">
    Generated by System
</div>

</body>
</html>
